spring:
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    #content-type: text/html
    enabled: true
    encoding: UTF-8
    #mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html
    # excluded-view-names:
    # template-resolver-order:
    # view-names:
  datasource:
    password: 123456

    #spring.datasource.password=123456